### ISSUE TITLE
[Feature Request] local run command with restart

### ISSUE THREAD

**Issue by nicolaskruchten** [andrew-hossack/dash-tools#37]
When I develop Dash apps, I almost always run them with `while true; do python app.py; sleep 1; done` such that if, while I'm typing, I save a file with, say, a syntax error, I can just glance at the console, see the error, fix it and save the file again and the app reboots. If I don't do this, the first syntax error crashes the app and I need to switch to my terminal and re-execute `python app.py`.

So the feature request is a command like `dashtools run` (which does the equivalent of `python app.py`) and `dashtools run --restart` (which does the equivalent of my restart loop, perhaps with a numeric argument for how many seconds to wait or something). 

`dashtools` could do some cool stuff like parse the output and apply nice colors, or even parse the output and notice that it's the same as the last crash and just increment a counter saying "app crashed N times with the error above" or whatever, to make it a nicer developer experience.

**Comment by andrew-hossack** [comment]
Hi @nicolaskruchten, first off thanks for your feature request. I'm a fan of the `dashtools run --restart` option, and will include that in a later version. Is `while true; do python app.py; sleep 1; done` a shell command that you run on linux? Does the console output spam error messages each second if one is encountered? 

One possibility for implementation would be to manage app execution in a python loop, capture console output and apply formatting / crash counter as you suggest. If you like, I can start a new branch `ah-add-run-restart-option` if you want to provide feedback before it gets merged?

**Comment by nicolaskruchten** [comment]
(note: I don't have access to a windows machine, so I'd need a hand making sure it works there)

**Comment by andrew-hossack** [comment]
Awesome, definitely feel free to fork & open a PR, I'd be happy to review! 

I could add you as a contributor to this project with branch create permission if you wish, else the project should already be set up to allow pull requests from forks. Let me know what works best.

**Comment by andrew-hossack** [comment]
Hey @nicolaskruchten, hope things are going well. If you have any questions about DashTools I can answer feel free to reach out. Thanks!

**Comment by nicolaskruchten** [comment]
I'm sorrry I disappeared here! The summer got away from me :)

**Comment by andrew-hossack** [comment]
@nicolaskruchten oh no worries, I can keep this issue open if you are still interested?
