### ISSUE TITLE
[BUG] requirements.txt error

### ISSUE THREAD

**Issue by AveryData** [andrew-hossack/dash-tools#42]
When running the dashtools heroku --deploy, I constantly get this error

`dashtools: Required file requirements.txt not found. Create one automatically?
dashtools: Continue? (y/n) > y
dashtools: Creating requirements.txt
Usage:
    pipreqs [options] [<path>]
dashtools: Error creating requirements.txt
dashtools: Are you in a valid dash app directory?
dashtools: Exiting`

I'm on windows. I'm not using a virtual environment so I think that has something to do with it?

I've even made the requirements.txt file myself and still get that error.

Could be because I'm multiple pages as well.

Maybe my folder setup is wrong?

![image](https://user-images.githubusercontent.com/33168903/178573494-06d44801-80c9-4b7e-9121-b960106efde2.png)

**Comment by AveryData** [comment]
I just tried using a template and deploying that and got the same error. So don't think it's my structure, must be environment?

**Comment by andrew-hossack** [comment]
Hello @AveryData, what directory are you running the `dashtools heroku --deploy` command from? You could be seeing that error if you do not cd into the project root directory before running the command.

**Comment by AveryData** [comment]
Hi @andrew-hossack, Saw that note in the READ.me, I'm in the project root directory.
