### ISSUE TITLE
[BUG] Application error 

### ISSUE THREAD

**Issue by Enoch768** [andrew-hossack/dash-tools#45]
Thank you so much for helping improve the quality of dash-tools!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
I deployed a multipage app with dashtools but it keep showing application error 
Please provide us your environment, so we can easily reproduce the issue.

- replace the result of `dash-tools --version` below

```
1.2
```

- please tell us what operating system you are using

```
[e.g. mac]
```

**Describe the bug**

**Expected behavior**

**Screenshots**

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by andrew-hossack** [comment]
Hi @Enoch768, so just to clarify, you ran:

`dashtools init MyApp multipage`

then ran the app either with:

`cd MyApp`
`dashtools run`

OR

`cd MyApp`
`python src/app.py`

What was the application error you encountered?
