### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alvelda** [andrew-hossack/dash-tools#47]
Thank you so much for helping improve the quality of dash-tools!

We do our best to catch bugs during the release process, but we rely on your help to find the ones that slip through.

**Describe your context**
Please provide us your environment, so we can easily reproduce the issue.

- replace the result of `dash-tools --version` below

```
1.2.1
```

- please tell us what operating system you are using

```
MAC OS  Monteray 12.4
```

**Describe the bug**

Brew installer doesn't set up path variable, not clear where executable is to invoke the dash-tools command is so as to add it to the Path.

installed a file tree at 
/Users/alvelda/anaconda/envs/python38/lib/python3.8/site-packages

where's the executable?

**Expected behavior**

I would have expected the path variable to be updated by the installation script.

If applicable, add screenshots or screen recording to help explain your problem.

**Comment by andrew-hossack** [comment]
Hi @alvelda, just to get a better understanding of your problem, you used Brew to install the package and are unable to run the `dashtools` command?

**Comment by alvelda** [comment]
Yes, that’s correct.

**Comment by andrew-hossack** [comment]
@alvelda, try uninstalling and re-installing directly from pip:

`pip install dash-tools`

Pip handles the CLI entry point when it is installed. I'm not sure how Brew works to install pip packages. Let me know what you find and I can update the docs.

**Comment by alvelda** [comment]
Okay, that worked, but now I get " Invalid Heroku App name whether I create one or use one of the default random names.

**Comment by andrew-hossack** [comment]
@alvelda thanks for providing that feedback. Looks like Heroku changed how their sever responds to unavailable app names behind the scenes. I've pushed out an update for **Version 1.7.3** so go ahead and run:

`pip install dash-tools --upgrade`

Let me know if this helps!
