### ISSUE TITLE
missing file in requirements file

### ISSUE THREAD

**Issue by Coding-with-Adam** [andrew-hossack/dash-tools#54]
Bug reported in a Youtube message on August 14, 2022, on the Charming Data channel in [this video](https://www.youtube.com/watch?v=RsiQHNRDcUA).

Form @1DS20CS083 _Harsha S:
@Andrew H  OMG aren't you the guy who made this? Thank you so much fam. It used to take a hour to upload stuff before, now it takes like a few minutes :D, thank you kind sir

P.s. there is a small error when I use pymongo in the project, it needs dnspython module to work. When I deploy the app in the requirements file, it only has the pymongo module but ignores the dnspython module so the website doesn't work. I fixed this issue easily by adding the dnspython module in the requirements file but I thought I would let you know.

**Comment by andrew-hossack** [comment]
@Coding-with-Adam dnspython in pymongo is specified as an optional dependency: https://github.com/mongodb/mongo-python-driver#dependencies and therefore was not picked up by pipreqs
