### ISSUE TITLE
[Feature Request] Deploying a dash app with GIFs

### ISSUE THREAD

**Issue by Pranshul-Sardana** [andrew-hossack/dash-tools#70]
**Is your feature request related to a problem? Please describe.**
I work with video datasets and I don't know about a good way of deploying videos/gifs using dash. I am using dash-gif-component  for creating a dash app with GIFs and I tried dash-tools advanced template. The app was working locally but the path was broken when deployed on Heroku.

Is there a way to deploy a GIF app to Heroku?

**Additional context**

**Comment by andrew-hossack** [comment]
Hey @Pranshul-Sardana you will need to add a "static" directory to include gifs and images. Check out https://dash.plotly.com/dash-enterprise/static-assets

**Comment by Pranshul-Sardana** [comment]
Thanks for sharing it. I am already keeping my png and gif files in assets and its subfolders. This is working locally but stops working when I deploy it to Heroku.

**Comment by andrew-hossack** [comment]
Check out https://community.plotly.com/t/deploying-your-dash-app-to-heroku-the-magical-guide/46723 under **HEROKU PITFALL: Serving static files does not work** for a potential solution!

**Comment by andrew-hossack** [comment]
Closed as this issue isn't dashtools related (related to plotly dash)
