### ISSUE TITLE
[Feature Request] deploy to another service besides heroku since free tier is no longer available

### ISSUE THREAD

**Issue by lundeen-bryan** [andrew-hossack/dash-tools#81]
Thanks so much for dash-tools!

**Is your feature request related to a problem? Please describe.**
Based on the post by [Heroku](https://blog.heroku.com/next-chapter) on their blog, it will no longer be possible to have a free account.  I would like to request information on how I could deploy to another free site, if there are any. I'm open to any suggestions, but perhaps netlify would work. 

**Describe the solution you'd like**
Again, a possible solution is to deploy to netlify. 

**Describe alternatives you've considered**
I"m not aware of any working alternatives than to pay for Heroku. 

**Additional context**
n/a

**Comment by andrew-hossack** [comment]
> Thanks so much for dash-tools!
> 
> **Is your feature request related to a problem? Please describe.** Based on the post by [Heroku](https://blog.heroku.com/next-chapter) on their blog, it will no longer be possible to have a free account. I would like to request information on how I could deploy to another free site, if there are any. I'm open to any suggestions, but perhaps netlify would work.
> 
> **Describe the solution you'd like** Again, a possible solution is to deploy to netlify.
> 
> **Describe alternatives you've considered** I"m not aware of any working alternatives than to pay for Heroku.
> 
> **Additional context** n/a

Hey @lundeen-bryan check out the `dashtools gui` and let me know what you think!
